language: android
jdk:
  - oraclejdk8
sudo: true
before_install:
- chmod +x gradlew
env:
  global:
   - ANDROID_API_LEVEL=25
   - EMULATOR_API_LEVEL=21
   - ANDROID_BUILD_TOOLS_VERSION=25.0.0
   - ANDROID_ABI=google_apis/armeabi-v7a
   - ADB_INSTALL_TIMEOUT=8 # minutes (2 minutes by default)
android:
  components:
    - tools
    - platform-tools
    - build-tools-$ANDROID_BUILD_TOOLS_VERSION
    - android-$ANDROID_API_LEVEL
    - android-$EMULATOR_API_LEVEL
    - extra
    - addItems-on
    - extra-google-m2repository
    - extra-android-m2repository
    - extra-android-support

    - addon-google_apis-google-$ANDROID_API_LEVEL
    - addon-google_apis-google-$EMULATOR_API_LEVEL

    - sys-img-armeabi-v7a-addon-google_apis-google-$ANDROID_API_LEVEL
    - sys-img-armeabi-v7a-addon-google_apis-google-$EMULATOR_API_LEVEL
  licenses:
    - 'android-sdk-preview-license-52d11cd2'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'
